name: tekartik_firebase_auth_node
description: Firebase auth server node
version: 0.9.0
publish_to: none

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  collection: '>=1.14.10'
  js: any
  uuid: '>=1.0.0'
  tekartik_firebase_auth:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart2
    version: '>=0.9.0'
  tekartik_firebase_node:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_node
      ref: dart2
    version: '>=0.4.0+0'
  firebase_functions_interop: ">=1.0.0-dev.11.0"
  firebase_admin_interop: ">=1.1.0"

dev_dependencies:
  test: ">=1.2.0"
  dev_test: '>=0.12.0-dev.1'
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
  build_runner: ">=0.9.1"
  build_node_compilers: ">=0.1.8"
  build_test: ">=0.10.3"
  process_run: '>=0.10.0+1'
  tekartik_app_node_build:
    git:
      url: git://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart2
    version: '>=0.1.0'

dependency_overrides:
  tekartik_firebase_auth_test:
    path: ../auth_test
  tekartik_firebase_auth:
    path: ../auth
  quiver_hashcode: '>=1.0.0'
#  firebase_admin_interop:
#    git: git://github.com/asaarnak/firebase-admin-interop