# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2

enable-beta-ecosystems: true

updates:
  - package-ecosystem: "pub"
    directory: "auth"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "auth_browser"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "auth_jwt"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "auth_local"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "auth_rest"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "auth_sembast"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "auth_test"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "repo_support"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
