# Created with https://github.com/dart-lang/mono_repo
language: dart

sudo: required
addons:
  chrome: stable

jobs:
  include:
    - stage: analyzer_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="auth"
    - stage: analyzer_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="auth_browser"
    - stage: analyzer_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="auth_node"
    - stage: analyzer_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="auth_test"
    - stage: analyzer_and_format
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="auth_local"
    - stage: test_vm
      script: ./tool/travis.sh test_vm
      env: PKG="auth"
    - stage: test_vm
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="auth_test"
    - stage: test_vm
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="auth_local"
    - stage: test_browser
      script: ./tool/travis.sh test_browser
      env: PKG="auth"
    - stage: test_browser
      script: ./tool/travis.sh test_browser
      env: PKG="auth_local"

stages:
  - analyzer_and_format
  - test_vm

# Only building master means that we don't run two builds for each pull request.
# branches:
#  only:
#    - master
#    - dart2

cache:
  directories:
    - $HOME/.pub-cache