language: dart
dart:
  - stable
  - beta
  - dev
# before_script:
#  - source $(pub run chrome_travis:env_rc)

sudo: required
addons:
  chrome: stable

script:
  - cd repo_support
  - dart pub get
  - dart run tool/travis.dart

cache:
  directories:
    - $HOME/.pub-cache