name: tekartik_firebase_auth_repo
description: Firebase auth repo (tools)
version: 0.5.1-dev.0
publish_to: none

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: '>=0.12.0-dev.1'
  grinder:
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.5.8'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.4'

  # test dependencies without version
  tekartik_firebase_auth_browser:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth_browser
      ref: dart2
  tekartik_firebase_auth_node:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth_node
      ref: dart2

