name: tekartik_firebase_auth
description: Firebase auth core
version: 0.9.0

publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  meta:
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2_3
    version: '>=0.4.0+0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.10.2+1'

dev_dependencies:
  process_run: '>0.10.0'
  test: "^1.0.0"
  dev_test: