name: tekartik_firebase_auth
description: Firebase auth core
version: 0.5.0+0
author: alex <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta:
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.4.0+0'
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.10.2+1'

dev_dependencies:
  test: "^1.0.0"
