name: tekartik_firebase_auth_local
description: Firebase local test
version: 0.10.1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  uuid: '>=1.0.0'
  sembast: ">=3.7.4+3"
  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart3a
    version: '>=0.9.1'
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: dart3a
    version: '>=0.4.0+0'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase

dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  tekartik_firebase_auth_test:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth_test
      ref: dart3a
    version: '>=0.8.0'
  build_runner: ">=2.4.13"
  build_test: ">=0.10.9+1"
  build_web_compilers: ">=4.0.11"
  process_run: ">=1.2.1+1"

resolution: workspace
