name: tekartik_firebase_auth_local
description: Firebase local test
version: 0.3.9
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase_auth:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart2
    version: '>=0.3.8'
  tekartik_firebase_local:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: dart2
    version: '>=0.3.9'
  test: ">=1.0.0"

dev_dependencies:
  dev_test: '>=0.12.0-dev.1'
  tekartik_firebase_auth_test:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth_test
      ref: dart2
    version: '>=0.3.8'

dependency_overrides:
  tekartik_firebase_auth:
    path: ../auth
  tekartik_firebase_auth_test:
    path: ../auth_test