name: tekartik_firebase_auth_local
description: Firebase local test
version: 0.5.0+3
publish_to: none

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase_auth:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart2
    version: '>=0.5.0+3'
  tekartik_firebase_local:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: dart2
    version: '>=0.4.0+0'
  test: ">=1.0.0"

dev_dependencies:
  dev_test: '>=0.12.0-dev.1'
  tekartik_firebase_auth_test:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth_test
      ref: dart2
    version: '>=0.5.0+3'

dependency_overrides:
  tekartik_firebase_auth:
    path: ../auth
  tekartik_firebase_auth_test:
    path: ../auth_test