name: tekartik_firebase_auth_sim
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  cv: ">=1.1.0+4"
  synchronized:
  tekartik_firebase_sim:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_sim
  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
  tekartik_firebase_auth_sembast:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth_sembast
  # path: ^1.8.0
  sembast: ">=3.7.4+3"
  path: ">=1.9.0"
  tekartik_app_cv_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_cv_sembast
  tekartik_app_rx:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_rx
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_local
  tekartik_app_web_socket:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_web_socket
dev_dependencies:
  lints: ">=5.0.0"
  tekartik_firebase_auth_test:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth_test
  test: ">=1.24.0"
resolution: workspace
