name: tekartik_firebase_auth_flutter
description: Firebase auth flutter
version: 0.8.1
environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tekartik_firebase_auth:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart2
    version: '>=0.8.0'
  tekartik_firebase_flutter:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_flutter
      ref: dart2
    version: '>=0.4.0+0'
  firebase_auth: '>=0.14.0+5'
  google_sign_in: '>=4.0.7'
dev_dependencies:
  flutter_test:
    sdk: flutter
  process_run: '>=0.10.3'

dependency_overrides:
  pedantic: '>=1.9.0'
  tekartik_firebase_auth:
    path: ../auth
  tekartik_firebase_auth_test:
    path: ../auth_test