name: tekartik_firebase_auth_sembast
description: Local auth on top of sembast
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  sembast: ">=3.7.4+3"
  cv: ">=1.1.0+4"
  tekartik_app_cv_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_cv_sembast
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase
  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      ref: dart3a
      path: auth
  tekartik_firebase_auth_local:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth_local
      ref: dart3a
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase_local
  path: ">=1.9.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dev_dependencies:
  lints: ">=5.0.0"
  tekartik_firebase_auth_test:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      ref: dart3a
      path: auth_test
  test: '>=1.24.0'

resolution: workspace
