# Copy this file as "local.config.yaml" in the same folder (.gitignored)
projectId: [YOUR-FIREBASE-PROJECT-ID]
apiKey: [YOURS]
authDomain: [YOURS]
databaseURL: [YOURS]
storageBucket: [YOURS]
messagingSenderId: [YOURS]