name: tekartik_firebase_auth_test
description: Firebase auth test
version: 0.9.0
author: alex <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  meta:
  path:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
  version: '>=0.4.0+0'
  tekartik_firebase_auth:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart2
    version: '>=0.9.0'
  test: ">=1.0.0"

dev_dependencies:
  process_run: '>=0.10.0+1'
  dev_test: '>=0.12.0-dev.1'

dependency_overrides:
  tekartik_firebase_auth:
    path: ../auth