name: tekartik_firebase_auth_test
description: Firebase auth test
version: 0.3.8
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  meta:
  path:
  uuid: '>=1.0.0'
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.3.7'
  tekartik_firebase_auth:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart2
    version: '>=0.3.8'
  test: ">=1.0.0"

dev_dependencies:
  dev_test: '>=0.12.0-dev.1'

dependency_overrides:
  tekartik_firebase_auth:
    path: ../auth