# tekartik analysis_options extension to pedantic
include: package:tekartik_common_utils/pedantic/analysis_options.strong_mode.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
#   exclude:
#     - path/to/excluded/files/**
