name: tekartik_firebase_auth_jwt
description: Firebase JWT auth validation.
version: 0.3.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.6.0
  corsac_jwt: '>=1.0.0-0'
  http:
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: null_safety
    version: '>=0.4.0+0'

  tekartik_firebase_auth:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: null_safety
    version: '>=0.1.0'

  rsa_pkcs: '>=1.1.2'
  tekartik_http:
    git:
      url: git://github.com/tekartik/http.dart
      path: http
      ref: null_safety
    version: '>=0.5.5'
  tekartik_app_crypto:
    git:
      url: git://github.com/tekartik/app_common_utils.dart
      ref: null_safety
      path: app_crypto
    version: '>=0.1.0'
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  dev_test:
  process_run:
  build_runner:
  build_test: ">=0.10.8"
  build_web_compilers:
  tekartik_firebase_browser:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_browser
      ref: null_safety
    version: '>=0.1.0'
  tekartik_firebase_auth_browser:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth_browser
      ref: null_safety
    version: '>=0.1.0'
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: null_safety
    version: '>=0.1.0'
dependency_overrides:
#  tekartik_firebase_auth_browser:
#    path: ../auth_browser
#  tekartik_firebase_auth:
#    path: ../auth
#  tekartik_firebase_auth_rest:
#    path: ../auth_rest