name: tekartik_firebase_auth_jwt
description: Firebase JWT auth validation.
version: 0.1.2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  corsac_jwt: '>=0.2.2'
  http:
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart2
    version: '>=0.4.0+0'
  rsa_pkcs: '>=1.1.2'
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  process_run:
  build_runner:
  build_test: ">=0.10.8"
  build_web_compilers:

dependency_overrides:
  tekartik_firebase_auth_browser:
    path: ../auth_browser
  tekartik_firebase_auth:
    path: ../auth
  tekartik_firebase_auth_rest:
    path: ../auth_rest
