name: tekartik_firebase_auth_jwt
description: Firebase JWT auth validation.
version: 0.4.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  web: '>=0.5.0'
  path: ">=1.9.0"
  corsac_jwt: '>=2.0.1'
  http:
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
    version: '>=0.4.0+0'

  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
    version: '>=0.1.0'

  rsa_pkcs: '>=1.1.2'
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
    version: '>=0.5.5'
  tekartik_app_crypto:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_crypto
    version: '>=0.1.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
dev_dependencies:
  test: ">=1.24.0"
  yaml: ">=3.1.2"
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  build_runner: ">=2.4.13"
  build_test: ">=0.10.8"
  build_web_compilers: ">=4.0.11"
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
    version: '>=0.1.0'
dependency_overrides:
resolution: workspace
#  tekartik_firebase_auth_browser:
#    path: ../auth_browser
#  tekartik_firebase_auth:
#    path: ../auth
#  tekartik_firebase_auth_rest:
#    path: ../auth_rest
