name: tekartik_firebase_auth_jwt
description: Firebase JWT auth validation.
version: 0.4.0
publish_to: none

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  web: '>=0.5.0'
  path: '>=1.6.0'
  corsac_jwt: '>=1.0.0-0'
  http:
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.4.0+0'

  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart3a
    version: '>=0.1.0'

  rsa_pkcs: '>=1.1.2'
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart3a
    version: '>=0.5.5'
  tekartik_app_crypto:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_crypto
    version: '>=0.1.0'
dev_dependencies:
  test: ^1.6.0
  yaml:
  dev_build:
  process_run:
  build_runner:
  build_test: ">=0.10.8"
  build_web_compilers:
  tekartik_firebase_browser:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_browser
      ref: dart3a
    version: '>=0.1.0'
  tekartik_firebase_auth_browser:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth_browser
      ref: dart3a
    version: '>=0.1.0'
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
    version: '>=0.1.0'
dependency_overrides:
#  tekartik_firebase_auth_browser:
#    path: ../auth_browser
#  tekartik_firebase_auth:
#    path: ../auth
#  tekartik_firebase_auth_rest:
#    path: ../auth_rest
