name: firebase_auth_repo_support
description: Firebase repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dev_dependencies:
  path:
  pub_semver:
  process_run: '>=0.10.3'
  tekartik_build_utils:
    git:
      url: https://github.com/tekartik/build_utils.dart
      ref: dart3a
    version: '>=0.7.8'
  fs_shim:
  test:
  dev_test:

