name: firebase_auth_repo_support
description: Firebase repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.8.0

dev_dependencies:
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"
  process_run: ">=1.2.1+1"
  tekartik_build_utils:
    git:
      url: https://github.com/tekartik/build_utils.dart
      ref: dart3a
    version: '>=0.7.8'
  fs_shim: ">=2.3.3+1"
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
resolution: workspace

