name: tekartik_firebase_auth_browser
description: Firebase auth browser
version: 0.10.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart3a
    version: '>=0.9.0'
  tekartik_firebase_browser:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_browser
      ref: dart3a
    version: '>=0.9.0'
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
    version: '>=0.1.0'
  googleapis_auth:
  service_worker:
  firebase: '>=7.0.0'
  web: '>=0.5.0'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a

dev_dependencies:
  test: ">=1.5.0"
  dev_build: '>=0.12.0-dev.1'
  http: any
  yaml: any
  build_runner: ">=1.6.0"
  build_test: ">=0.10.8"
  build_web_compilers: ">=2.4.0"
  process_run: '>=0.10.3'
  tekartik_firebase_auth_test:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth_test
      ref: dart3a
    version: '>=0.9.0'

dependency_overrides:
  tekartik_firebase_auth:
    path: ../auth
  tekartik_firebase_auth_test:
    path: ../auth_test
