name: tekartik_firebase_auth_browser
description: Firebase auth browser
version: 0.5.0+4
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  tekartik_firebase_auth:
    git:
      url: git://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart2
    version: '>=0.5.0+4'
  tekartik_firebase_browser:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_browser
      ref: dart2
    version: '>=0.4.0+0'
  firebase: '>=5.0.2'
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2
  googleapis_auth:
  service_worker:

dev_dependencies:
  test: ">=0.12.37"
  dev_test: '>=0.12.0-dev.1'
  http: any
  yaml: any
  build_runner: ">=0.9.1"
  build_test: ">=0.10.3"
  build_web_compilers: ">=0.4.0+4"
  process_run: '>=0.10.0+1'

dependency_overrides:
  tekartik_firebase_auth:
    path: ../auth
  tekartik_firebase_auth_test:
    path: ../auth_test